### ISSUE TITLE
Standalone builds won't send Mixpanel events

### ISSUE THREAD

**Issue by manituan** [mixpanel/mixpanel-unity#108]
I've been debugging this issue for 2 days and I don't think I can fix it on my own. I hope you can help me out. 

Mixpanel works on the editor and on Android/iOS builds, but not on Standalone builds.

There are no errors in the console. We target IL2CPP, .NET 4.6. We've tried Unity 2018.4 and 2019.4 versions and Mixpanel 2.0 and 2.2.1. All yielding the same result. 

I'd be more than happy to answer any specific question you may have. Thanks.

**Comment by manituan** [comment]
After I wrote this down I realised I haven't tested it on a Mono build. And it works there... 
Could you help me fixing this out?

**Comment by patedit** [comment]
Hi @manituan - have you tried turning debugging on? What do you see on the console? (Edit -> Project Settings -> Mixpanel)

**Comment by manituan** [comment]
This is coming from a Debug IL2CPP Standalone build:

`[Mixpanel] System.InvalidOperationException: End of file reached while trying to read queue item
  at mixpanel.queue.PersistentQueue.ReadEntriesFromFile (mixpanel.queue.PersistentQueueEntry firstEntry, System.Int64 currentBufferSize) [0x00000] in <00000000000000000000000000000000>:0 
  at mixpanel.queue.PersistentQueue.ReadAhead () [0x00000] in <00000000000000000000000000000000>:0 
  at mixpanel.queue.PersistentQueue.Dequeue () [0x00000] in <00000000000000000000000000000000>:0 
  at mixpanel.queue.PersistentQueueSession.Dequeue () [0x00000] in <00000000000000000000000000000000>:0 
  at mixpanel.Worker+<SendData>d__19.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
  at mixpanel.Worker.DispatchOperations () [0x00000] in <00000000000000000000000000000000>:0 
  at mixpanel.Worker.RunBackgroundThread () [0x00000] in <00000000000000000000000000000000>:0 
  at Valve.VR.IVRCompositor+_ForceReconnectProcess.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x00000] in <00000000000000000000000000000000>:0 
  at Valve.VR.IVRCompositor+_ForceReconnectProcess.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
mixpanel.Mixpanel:LogError(String)
mixpanel.Worker:RunBackgroundThread()
Valve.VR._ForceReconnectProcess:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
Valve.VR._ForceReconnectProcess:Invoke()`

One month ago we got this similar error log:

`[Mixpanel] System.InvalidOperationException: End of file reached while trying to read queue item
  at mixpanel.queue.PersistentQueue.ReadEntriesFromFile (mixpanel.queue.PersistentQueueEntry firstEntry, System.Int64 currentBufferSize) [0x00000] in <00000000000000000000000000000000>:0 
  at mixpanel.queue.PersistentQueue.ReadAhead () [0x00000] in <00000000000000000000000000000000>:0 
  at mixpanel.queue.PersistentQueue.Dequeue () [0x00000] in <00000000000000000000000000000000>:0 
  at mixpanel.queue.PersistentQueueSession.Dequeue () [0x00000] in <00000000000000000000000000000000>:0 
  at mixpanel.Worker+<SendData>d__19.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
  at mixpanel.Worker.DispatchOperations () [0x00000] in <00000000000000000000000000000000>:0 
  at mixpanel.Worker.RunBackgroundThread () [0x00000] in <00000000000000000000000000000000>:0 
  at OVR.OpenVR.IVRCompositor+_ClearSkyboxOverride.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x00000] in <00000000000000000000000000000000>:0 
  at OVR.OpenVR.IVRCompositor+_ClearSkyboxOverride.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
mixpanel.Mixpanel:LogError(String)
mixpanel.Worker:RunBackgroundThread()
OVR.OpenVR._ClearSkyboxOverride:Invoke()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
OVR.OpenVR._ClearSkyboxOverride:Invoke()`

**Comment by patedit** [comment]
I've seen that before. It's a known issue with how we store/read from files. Could you reach out to support@mixpanel.com about it to track this issue with you? You can link this github ticket and that'll be enough. Thanks a ton

**Comment by manituan** [comment]
done. Thanks

**Comment by MohHeader** [comment]
I think I have the same issue, sent an email to support, but received the following response

> 
> We’ve recently changed our support structure. If you're currently on a free plan, this may affect you. Please see our updated support policy for more details.
> 
> If your company is on a paid plan with Mixpanel, please reply back with the email associated with your Mixpanel account so we can reopen your ticket and have the information needed to answer your questions quickly.

so mostly the ticket had been closed :(

**Comment by manituan** [comment]
I contacted them and they ended adding this issue to their backlog. Pretty disappointing outcome. 

Now we can't track Standalone events. That's not something I'd put in the backlog, to be honest.

**Comment by tomkrikorian** [comment]
Hi,
I'm pretty sure i'm having the same issue currently for Oculus Rift / Oculus Quest (With link) builds. Any news on a fix ? 
It's very disturbing to see such a big issue not fixed months after a report.

**Comment by manituan** [comment]
@tomkrikorian I saw your reply on my email and I realised I didn't comment with our solution. I hope it's useful.

Mixpanel pretty much told us that they won't work on this, anytime soon, as standalone Unity users are a tiny fraction of their user base. 

What we've done is to stop using Mixpanel for Unity and get Mixpanel-csharp from NuGet. It works perfectly now.

**Comment by tomkrikorian** [comment]
I got the same answer which is crazy... I managed to fix my issues by removing their PersistentQueue implementation (DiskQueue library) from their SDK.

I'll use the nuget package instead, seems like a way better option.

**Comment by manubkool** [comment]
We found the same issue, and after speaking with them, it seems that they will be fixing this issue soon, around OCTOBER-2021.

**Comment by zihejia** [comment]
Yes! we are working on it. Sorry for all the inconvenience.

**Comment by wiurxee** [comment]
Hi, 
After upgrading to v3.0.1 I noticed that there is a change in the code that instantiates the mixpanel controller, now the mixpanel gameobject is not marked with DontDestroyOnLoad flag. Indeed v.3.01 fixes the problem with the persistentqueue and it has started logging events, but when changing between scenes the object might be destroyed.
